services:
  postgresdb:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./src/main/resources/schema-all.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRESDB_USER"]
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    image: batch-processing
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: no

volumes:
  postgres-volume:
